{
  "name": "@klipitkas/await-to",
  "version": "0.1.0",
  "description": "Solve the try-catch hell using golang style error handling.",
  "private": false,
  "publishConfig": {
	  "access": "public"
  },
  "main": "index.js",
  "directories": {
    "test": "test"
  },
  "scripts": {
    "test": "jest"
  },
  "files": ["*"],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "jest": "^27.2.1"
  },
  "jest": {
   "testRegex": "(/__tests__/.*|\\.(test))\\.(js)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js"
    ],
    "coveragePathIgnorePatterns": [
      "/node_modules/",
      "/tests/"
    ],
    "coverageThreshold": {
      "global": {
        "branches": 90,
        "functions": 95,
        "lines": 95,
        "statements": 95
      }
    }
  }
}
